# docker-compose.dev.yml
# run locally with `docker compose -f docker-compose.dev.yml up`
# this is for development only, does not include the tor service.
services:
  caddy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: