name: Release CLI

on:
  push:
    tags:
      - "v*"
      - "!v*-win"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build Linux
        run: go build -ldflags "-X github.com/neozmmv/Lighthouse/cli/cmd.version=${{ github.ref_name }}" -o lighthouse-linux-amd64
        working-directory: cli

      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/neozmmv/Lighthouse/cli/cmd.version=${{ github.ref_name }}" -o lighthouse-darwin-amd64
        working-directory: cli

      - name: Build Linux ARM
        run: GOOS=linux GOARCH=arm64 go build -ldflags "-X github.com/neozmmv/Lighthouse/cli/cmd.version=${{ github.ref_name }}" -o lighthouse-linux-arm64
        working-directory: cli

      - name: Build macOS ARM (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -ldflags "-X github.com/neozmmv/Lighthouse/cli/cmd.version=${{ github.ref_name }}" -o lighthouse-darwin-arm64
        working-directory: cli

      - name: Create new Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Lighthouse ${{ github.ref_name }}"
          files: |
            cli/lighthouse-linux-amd64
            cli/lighthouse-linux-arm64
            cli/lighthouse-darwin-amd64
            cli/lighthouse-darwin-arm64
            docker-compose.yml
            Caddyfile
            install.sh
            uninstall.sh
